### ISSUE TITLE
/var/log/pki/pki-tomcat/ca/debug.*.log files are not cleaned up

### ISSUE THREAD

**Issue by opoplawski** [dogtagpki/pki#3731]
This is from an IPA install.  See also https://pagure.io/freeipa/issue/8971.

I have lots of debug.DATE.log files in /var/log/pki/pki-tomcat. These should get cleaned up automatically.
Version/Release/Distribution
```
ipa-server-4.9.2-4.module_el8.4.0+846+96522ed7.x86_64
ipa-client-4.9.2-4.module_el8.4.0+846+96522ed7.x86_64
389-ds-base-1.4.3.16-19.module_el8.4.0+884+e9b25896.x86_64
pki-ca-10.10.5-3.module_el8.4.0+816+beb6e9a3.noarch
krb5-server-1.18.2-8.el8.x86_64
```

**Comment by yrro** [comment]
Looks like none of the log files in /var/log/pki are being rotated by anything. I have `catalina`, `localhost_access_log` etc dating back 8 months (on RHEL 8.5 with `pki-base-10.11.2-2.module+el8.5.0+12735+8eb38ccc.noarch`).

**Comment by maltewhiite** [comment]
My FreeIPA server is almost dying because of 
`-rw-r-----. 1 pkiuser pkiuser  70G Feb 11 11:59 debug`
What do I do? Can I safely delete the file? How do I remove this file without my FreeIPA server dying?

I inherited this FreeIPA from someone who is no longer at the company, and suddenly I have the responsibility for all user administration and maintenance of the FreeIPA server, and I only know Linux commands like cd and nano. 

What do I do?

**Comment by yrro** [comment]
> My FreeIPA server is almost dying because of `-rw-r-----. 1 pkiuser pkiuser 70G Feb 11 11:59 debug` which is located in `/var/log/pki/pki-tomcat/ca` What do I do? Can I safely delete the file?

I'm pretty sure you can truncate the file with the `truncate` command.

Can you post to freeipa-users about this - hopefully someone will know the proper way to check the PKI debug level & figure out why the file's not being rotated.

**Comment by yrro** [comment]
> My FreeIPA server is almost dying because of -rw-r-----. 1 pkiuser pkiuser 70G Feb 11 11:59 debug which is located in /var/log/pki/pki-tomcat/ca What do I do? Can I safely delete the file?

According to https://github.com/dogtagpki/pki/wiki/Configuring-Subsystem-Debug-Log these log files are rotated daily and purged after 7 days. But that doesn't happen for me either.

Here's a script I run daily to clean up these files as well as the other subsystem-specific log files which are not otherwise rotated.

```bash
#!/bin/bash

set -eu -o pipefail

DRY_RUN=${DRY_RUN:-1}
DEBUG_RETAIN_DAYS=${DEBUG_RETAIN_DAYS:-60}
RLF_RETAIN_DAYS=${RLF_RETAIN_DAYS:-14}

if [[ $DRY_RUN -ne 0 ]]; then
    echo 'This is a dry-run; no files will be removed'
fi

for subsystem in acme ca kra pki; do
    dir="/var/log/pki/pki-tomcat/$subsystem"

    # debug logs are rotated daily, so we can simply delete everything except
    # the last N logfiles
    (find "$dir" -name 'debug.????-??-??.log' -print0 || true) | LC_COLLATE=C sort -z | head -z -n "-$DEBUG_RETAIN_DAYS"

    # com.netscape.cms.logging.RollingLogFile logs are rotated after 30 days or
    # 2000 KiB; so we have to examine modification times to decide which files
    # to delete
    for logfile in selftests.log system transactions signedAudit/{ca_audit,kra_cert-kra_audit}; do
        path="$dir/$logfile"
        if [[ -f $path ]]; then
            datum=$(stat -c %Y "$path")
            find "$dir" -path "$path.*" -not -newermt "@$((datum - "$RLF_RETAIN_DAYS" * 86400))" -print0
        fi
    done
done \
    | \
while IFS= read -r -d $'\0' file _rest; do
    echo "Removing $file"
    if [[ $DRY_RUN -eq 0 ]]; then
        rm "$file"
    fi
done

# vim: ts=8 sts=4 sw=4 et
```

**Comment by nmaludy** [comment]
Same issue here. Would be great if they were cleaned up, or had a standard `logrotate` config.

**Comment by milaflq** [comment]
We are experiencing the same behavior and it causes problems.

This issue has been opened in 2021 and still no development on it.

Running "idm-pki-ca-10.14.3-1.module_el8.8.0+3499+bdda178f.noarch" and we don't see the log file rotation but it's configured in "logging.properties"

Is there any way to bump this issue so it's taken care of?

Thanks

**Comment by tomdus123** [comment]
We are experiencing the same behavior. 
`ipa --version` VERSION: 4.11.0, API_VERSION: 2.253

Any update on this issue?
Thanks Tomas

**Comment by yrro** [comment]
According to https://github.com/dogtagpki/pki/wiki/Configuring-Subsystem-Debug-Log#configuration the `org.apache.juli.FileHandler` is initialized with `maxDays` set to `7` and `prefix` set to `debug.`.

Within that class, the [clean method](https://github.com/apache/tomcat/blob/ca9b39f0a1e0086e9447d03a1c34d1528558a4b9/java/org/apache/juli/FileHandler.java#L472) is invoked when the class is created (i.e., when `pki-tomcat` starts).

It calls [streamFilesForDelete](https://github.com/apache/tomcat/blob/ca9b39f0a1e0086e9447d03a1c34d1528558a4b9/java/org/apache/juli/FileHandler.java#L488) to determine the list of files that should be deleted. This method filters all files in the object's `directory` by examining the filename to determine the file's date and comparing it to the current date - `maxDays` days.

The method that extracts a date from the filename is [obtainDateFromPath](https://github.com/apache/tomcat/blob/ca9b39f0a1e0086e9447d03a1c34d1528558a4b9/java/org/apache/juli/FileHandler.java#L509). This matches the log file name against [pattern](https://github.com/apache/tomcat/blob/ca9b39f0a1e0086e9447d03a1c34d1528558a4b9/java/org/apache/juli/FileHandler.java#L342). Any filenames that don't match are silently ignored.

The pattern would be initialized with something like (the string represented by the Java string literal) `"^(debug\.)\\d{4}-\\d{1,2}-\\d{1,2}(\.log)$"` which matches e.g., `debug.2024-10-22.log`.

The date is extracted using substring operations, taking into account the length of `prefix` and `suffix`. It's then parsed with [DateTimeFormatter.ISO_LOCAL_DATE](https://docs.oracle.com/en/java/javase/23/docs/api/java.base/java/time/format/DateTimeFormatter.html#ISO_LOCAL_DATE).

Matching files are deleted, and any `IOException`s thrown are reported via `java.util.logging.Handler.reportError` which in turn calls the object's associated `errorManager`'s `error` method. In this case `errorManager` is a `java.util.logging.ErrorHandler` which prints to `System.err`.

All of that is a lot of words to say: the code for deleting old debug messages looks fine and I don't see why it's not working!

**Comment by yrro** [comment]
I pointed `strace` at the [FileHandlerLogFilesCleaner-...](https://github.com/apache/tomcat/blob/ca9b39f0a1e0086e9447d03a1c34d1528558a4b9/java/org/apache/juli/FileHandler.java#L89) thread where the above runs and left it overnight.

This is an `ExecutorService` that's shared between all instances of `FileHander`. So as each subsystem's instance tries to log its first message of the day, we should see the thread listing the subsystems' subdirectory and removing old files.

This morning I saw:

```
# tail  -F /var/tmp/pki-logging.stace                                                                      
futex(0x7f8e1c1b7120, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY) = 0            
futex(0x7f8e1c1b70d0, FUTEX_WAKE_PRIVATE, 1) = 0
openat(AT_FDCWD</usr/share/tomcat>, "/var/lib/pki/pki-tomcat/logs/pki", O_RDONLY) = 89</var/log/pki/pki-tomcat/pki>
dup(89</var/log/pki/pki-tomcat/pki>)    = 109</var/log/pki/pki-tomcat/pki>
fstat(89</var/log/pki/pki-tomcat/pki>, {st_mode=S_IFDIR|0755, st_size=146, ...}) = 0
fcntl(89</var/log/pki/pki-tomcat/pki>, F_GETFL) = 0x8000 (flags O_RDONLY|O_LARGEFILE)
fcntl(89</var/log/pki/pki-tomcat/pki>, F_SETFD, FD_CLOEXEC) = 0
getdents64(89</var/log/pki/pki-tomcat/pki>, 0x7f8d8c14ed50 /* 7 entries */, 32768) = 248
close(89</var/log/pki/pki-tomcat/pki>)  = 0
close(109</var/log/pki/pki-tomcat/pki>) = 0
futex(0x7f8e1c1b7124, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY^C
```

This happened at 00:14 according to the timestamp on the log file:

```
$ ls -l /var/tmp/pki-logging.stace 
-rw-r--r--. 1 root root 860 Nov  1 00:14 /var/tmp/pki-logging.stace
```

So the `pki` subsystem logged a message, which _did_ cause `clean` to get called, triggering the thread to list files in `/var/log/pki/pki-tomcat/pki`. And it found 7 files. But it didn't go on to remove any of them.

```
# ll -a /var/log/pki/pki-tomcat/pki
total 720
drwxr-xr-x. 2 pkiuser pkiuser    118 Nov  1 08:15 .
drwxrwx---. 7 pkiuser pkiuser   4096 Nov  1 00:00 ..
-rw-r--r--. 1 pkiuser pkiuser  61465 Oct 22 15:00 debug.2024-10-22.log
-rw-r--r--. 1 pkiuser pkiuser  92035 Oct 30 23:45 debug.2024-10-30.log
-rw-r--r--. 1 pkiuser pkiuser 420028 Oct 31 23:56 debug.2024-10-31.log
-rw-r--r--. 1 pkiuser pkiuser 143416 Nov  1 08:12 debug.2024-11-01.log
```

There are now 6 files in the directory because my own log cleanup script removed `debug.2024-10-21.log` as it was 10 days old:

```
# journalctl -u pki-log-cleanup --since=today --no-hostname
Nov 01 01:39:31 systemd[1]: Starting pki log file cleanup...
Nov 01 01:39:31 systemd[1]: Started pki log file cleanup.
Nov 01 01:39:31 pki-log-cleanup[94101]: Deleting /var/log/pki/pki-tomcat/acme/debug.2024-10-21.log
Nov 01 01:39:31 pki-log-cleanup[94101]: Deleting /var/log/pki/pki-tomcat/ca/debug.2024-10-21.log
Nov 01 01:39:31 pki-log-cleanup[94101]: Deleting /var/log/pki/pki-tomcat/kra/debug.2024-10-21.log
Nov 01 01:39:31 pki-log-cleanup[94101]: Deleting /var/log/pki/pki-tomcat/pki/debug.2024-10-21.log
Nov 01 01:39:31 systemd[1]: pki-log-cleanup.service: Deactivated successfully.
```

So at the time the `clean` method was called, there would have been two files older than the configured [7 day](https://github.com/dogtagpki/pki/blob/1ee8f34643199e3eb608c67f38e740494baec953/base/server-webapp/webapps/pki/WEB-INF/classes/logging.properties#L26) cutoff limit, and neither were removed by `clean`.

**Comment by fmarco76** [comment]
This issue should already be fixed from dogtag version  >= 11.6 with the PR #4924 and I am closing this issue.

**Comment by yrro** [comment]
I'm still seeing this with `idm-pki-server-11.6.0-3.el9.noarch`.

My script runs every night to remove debug log files > 10 days old. If dogtag was removing old debug log files itself within 7 days, then there shouldn't be any log files for my script to clean up. But looking at today's output:

```
$ journalctl --since=today --no-hostname -t pki-log-cleanup
Nov 03 00:44:05 pki-log-cleanup[575564]: Deleting /var/log/pki/pki-tomcat/acme/debug.2025-10-23.log
Nov 03 00:44:05 pki-log-cleanup[575564]: Deleting /var/log/pki/pki-tomcat/ca/signedAudit/ca_audit.20250918072813
Nov 03 00:44:05 pki-log-cleanup[575564]: Deleting /var/log/pki/pki-tomcat/ca/debug.2025-10-23.log
Nov 03 00:44:05 pki-log-cleanup[575564]: Deleting /var/log/pki/pki-tomcat/kra/debug.2025-10-23.log
Nov 03 00:44:05 pki-log-cleanup[575564]: Deleting /var/log/pki/pki-tomcat/pki/debug.2025-10-23.log
```

... it cleaned up some 11-day old files. So those files weren't removed by dogtag.

**Comment by fmarco76** [comment]
@yrro Thanks for the feedback. I am reopening to verify if there are other problem with rotation.

**Comment by yrro** [comment]
FYI, I had a look for `AccessControlException` in journal messages for `pki-tomcatd@pki-tomcat.service` & didn't see anything in there. But I am not sure if I'm looking in the right place. Anyway, any hunting for log messages or debugging I can help with - please let me know.
